/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BUSQUEDA;

import PaqueteInterfaz.MainFrame;
import java.sql.ResultSet;
import java.sql.SQLException;


/**
 *
 * @author LUPITHAG
 */
public class SearchTable extends javax.swing.JPanel {

    ResultSet rs;
    MainFrame m;
    public BUSQUEDA.Encabezado cabeza;
    public SearchTable(MainFrame m) {
        cabeza = new BUSQUEDA.Encabezado();
        
        
        try {
            this.rs = new events().getAllQuery();
            initComponents();
            this.m=m;
            addToPanel(rs);
            
           

        } catch (SQLException ex) {
             }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setAutoscrolls(true);
        setLayout(new java.awt.GridLayout(50, 1));
    }// </editor-fold>//GEN-END:initComponents
    
    public void addToPanel(ResultSet r){
     
        this.removeAll();
        add(cabeza);
        validate();
        repaint();
        try {
             
            while (r.next()){
                registro reg = new registro (r.getInt("id"),r.getString("nombre"),
                                             r.getString("apellido"),r.getString("fechanacimiento"),
                                             r.getString("telefono"),r.getString("fechainsert"),this.m);
                add(reg);
            }
             validate();
             repaint();
        } catch (SQLException ex) {
           
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
