/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package componentesGraficos;

import javax.swing.JLabel;

/**
 *
 * @author Jorge Petris
 */
public class DienteGrande extends javax.swing.JPanel {

  /**
   * Creates new form DienteGrande
   */
  public DienteGrande(String s) {
    initComponents();
    jLabel1.setText(s);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel2 = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    jPanel1 = new javax.swing.JPanel();
    jSeparator1 = new javax.swing.JSeparator();

    jLabel2.setText("jLabel2");

    setBackground(new java.awt.Color(250, 250, 250));
    setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(166, 166, 166)));
    setMaximumSize(new java.awt.Dimension(89, 210));
    setMinimumSize(new java.awt.Dimension(89, 210));
    setPreferredSize(new java.awt.Dimension(89, 210));

    jLabel1.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(66, 66, 66));
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("D");
    jLabel1.setBorder(null);
    jLabel1.setMaximumSize(new java.awt.Dimension(100, 100));
    jLabel1.setMinimumSize(new java.awt.Dimension(100, 100));
    jLabel1.setPreferredSize(new java.awt.Dimension(100, 100));

    jPanel1.setBackground(new java.awt.Color(245, 245, 245));
    jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents

  
  private void updateDiente() {
    jPanel1.removeAll();
    for(int i=0 ; i<10 ; i++) {
      jPanel1.add(new lblDiente(procedimientos[i]));
    }
  }
  
  public void addElement(String procedimiento) {
    for(int i=0 ; i<10 ; i++) {
      if(procedimientos[i] == null) {
        procedimientos[i] = procedimiento;
        break;
      }
    }
    updateDiente();
  }
  
  public void removeAll() {
    for(int i=0 ; i<10 ; i++) {
      procedimientos[i] = null;
    }
    updateDiente();
  }

  private String[] procedimientos = new String[10];
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JSeparator jSeparator1;
  // End of variables declaration//GEN-END:variables
  
  private class lblDiente extends JLabel{
    
    lblDiente(String str) {
      this.setText(str);
      this.setSize(72, 20);
      this.setHorizontalAlignment(JLabel.CENTER);
      this.setVisible(true);
    }
  }
  
}
